name: Run Update Script

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "15 19 * * 0"
  #   - cron: "15 19 * * 2"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Installed package list
        run: apt list --installed
      - name: Remove Chrome
        run: sudo apt purge google-chrome-stable
      - name: Remove default Chromium
        run: sudo apt purge chromium-browser
      - name: Install a new Chromium
        run: sudo apt install -y chromium-browser

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          DP_ID: ${{ secrets.DP_ID }}
        run: python update.py

      - name: push changes
        uses: stefanzweifel/git-auto-commit-action@v5
